### ISSUE TITLE
studio page (internal): implement table

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#121] opened 2020-07-02 19:06 UTC
We're so excited about this table option! Things to add:

- Whether it passes the schema requirements (just a checkmark is fine)
- If they fill out the minutes tracker, then time spent on project
- Emojis used!

**Comment by jsarchibald** [comment] 2020-07-04 00:14
Duplicate of #26

**Closed by jsarchibald** 2020-07-04 00:14 UTC
Labels: duplicate, enhancement
