### ISSUE TITLE
delete links for old projects?

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#123] opened 2020-07-02 19:26 UTC
We deleted the schema + studios but the links to the projects seem to still persist? 

<img width="584" alt="Screenshot 2020-07-02 15 22 39" src="https://user-images.githubusercontent.com/5756274/86401564-6ed87b80-bc78-11ea-9c7d-e65a26250617.png">

**Comment by jsarchibald** [comment] 2020-07-03 21:09
Duplicate of #10

**Closed by jsarchibald** 2020-07-03 21:09 UTC
Labels: bug, duplicate
